'use strict';
let chatController=null,chatRequestId=null,chatDraftTimer=null,chatDraftDirty=false,chatProfile=null,recorder=null,recordingStream=null,recordingTimer=null,welcomeEntranceTimer=0,mascotStateTimer=0,activeSpeech=null,speechOperation=0;
const VEYRO_MASCOTS={black:{name:'Veyro Black',greeting:'Olá! Sou o Veyro Black. Estou pronto para conversar com você.'},blue:{name:'Veyro Blue',greeting:'Oi! Sou o Veyro Blue. Vamos descobrir e criar juntos?'},green:{name:'Veyro Green',greeting:'Olá! Sou o Veyro Green. Pode contar comigo.'},prime:{name:'Veyro Prime',greeting:'Saudações! Sou o Veyro Prime. Como posso ajudar?'}};
const VEYRO_VOICES={atlas:{name:'Veyro Atlas',gender:'Masculina',description:'Grave, firme e madura.',voice:'pt-BR-AntonioNeural'},neo:{name:'Veyro Neo',gender:'Masculina',description:'Clara, leve e ligeiramente aguda.',voice:'pt-BR-FabioNeural'},luna:{name:'Veyro Luna',gender:'Feminina',description:'Suave, doce e expressiva.',voice:'pt-BR-ThalitaNeural'},iris:{name:'Veyro Iris',gender:'Feminina',description:'Clara, séria e profissional.',voice:'pt-BR-FranciscaNeural'},rafael:{name:'Veyro Local',gender:'Masculina · Português',description:'Voz sintetizada no computador pelo Pocket TTS. O texto não é enviado a um serviço externo.',voice:'Pocket TTS · Rafael'}};
const MASCOT_KEY='veyro-mascot-v1',VOICE_KEY='veyro-voice-profile-v1',VOICE_AUTO_KEY='veyro-voice-auto-v1',VOICE_RATE_KEY='veyro-voice-rate-v1',VOICE_PITCH_KEY='veyro-voice-pitch-v1',VOICE_SPEED_KEY='veyro-voice-speed-v1';
function readPreference(key,fallback){try{return localStorage.getItem(key)||fallback;}catch{return fallback;}}
function readNumberPreference(key,fallback,min,max){const value=Number(readPreference(key,String(fallback)));return Number.isFinite(value)?Math.max(min,Math.min(max,value)):fallback;}
let selectedMascot=VEYRO_MASCOTS[readPreference(MASCOT_KEY,'black')]?readPreference(MASCOT_KEY,'black'):'black',selectedVoice=VEYRO_VOICES[readPreference(VOICE_KEY,'atlas')]?readPreference(VOICE_KEY,'atlas'):'atlas',voiceAutoRead=readPreference(VOICE_AUTO_KEY,'false')==='true',voiceRate=readNumberPreference(VOICE_RATE_KEY,0,-15,15),voicePitch=readNumberPreference(VOICE_PITCH_KEY,0,-6,6),voiceSpeed=readNumberPreference(VOICE_SPEED_KEY,1,0.75,1.5);
function mascotName(){return VEYRO_MASCOTS[selectedMascot].name;}
function currentVoiceProfile(){return state.ttsProvider==='pocket'?'rafael':selectedVoice;}
function renderMascot(){for(const node of document.querySelectorAll('.mascot-hero,.mascot-preview-portrait')){node.dataset.mascot=selectedMascot;node.setAttribute('aria-label',mascotName());}$('mascot-current-name').textContent=mascotName();$('mascot-preview-name').textContent=mascotName();$('mascot-greeting').textContent=VEYRO_MASCOTS[selectedMascot].greeting;for(const option of document.querySelectorAll('[data-mascot-choice]'))option.setAttribute('aria-pressed',String(option.dataset.mascotChoice===selectedMascot));$('voice-toggle').setAttribute('aria-pressed',String(voiceAutoRead));$('voice-toggle').setAttribute('aria-label',voiceAutoRead?'Desativar leitura automática':'Ativar leitura automática');$('voice-toggle').textContent=voiceAutoRead?'◖)) Auto on':'◖)) Auto off';$('voice-toggle').title=voiceAutoRead?'Leitura automática ativa':'Leitura automática desativada';}
function chooseMascot(id){if(!VEYRO_MASCOTS[id])return;selectedMascot=id;try{localStorage.setItem(MASCOT_KEY,id);}catch{}renderMascot();renderChatMessages();}
function openMascotPicker(){renderMascot();$('mascot-picker').showModal();}
function setMascotState(value){clearTimeout(mascotStateTimer);document.body.dataset.mascotState=value;const labels={idle:'Pronto para conversar',attention:'Estou ouvindo você',thinking:'Veyro está pensando…',speaking:'Veyro está respondendo…',reading:'Lendo a resposta em voz alta',done:'Resposta concluída'};$('mascot-status').textContent=labels[value]||labels.idle;if(value==='done')mascotStateTimer=setTimeout(()=>setMascotState('idle'),1800);}
function speechText(value){return String(value||'').replace(/```[\s\S]*?```/g,' ').replace(/`[^`]*`/g,' ').replace(/!\[([^\]]*)\]\([^)]*\)/g,'$1').replace(/\[([^\]]+)\]\([^)]*\)/g,'$1').replace(/^\s{0,3}#{1,6}\s+/gm,'').replace(/^\s*>\s?/gm,'').replace(/^\s*[-*+]\s+/gm,'').replace(/^\s*\d+[.)]\s+/gm,'').replace(/https?:\/\/\S+/g,'link').replace(/[|*_~]/g,' ').replace(/\s+/g,' ').trim();}
function releaseSpeech(){if(!activeSpeech)return;const old=activeSpeech;activeSpeech=null;if(old.audio){old.audio.pause();old.audio.removeAttribute('src');old.audio.load();}if(old.url)URL.revokeObjectURL(old.url);}
function stopSpeech(){speechOperation++;releaseSpeech();setMascotState('idle');renderChatMessages();}
async function requestSpeech(text,{messageId=null,profileId=currentVoiceProfile(),rate=voiceRate,pitch=voicePitch,speed=voiceSpeed,autoPlay=true,statusNode=null}={}){const clean=speechText(text);if(!clean){feedback('Esta resposta não contém texto narrável.',true);return;}if(clean.length>5000){feedback('Esta resposta passa do limite de 5.000 caracteres por áudio.',true);return;}if(!state.tts){feedback('Configure um provedor de voz no servidor para narrar respostas.',true);return;}const operation=++speechOperation;releaseSpeech();const pending={messageId,profileId,status:'loading',audio:null,url:null};activeSpeech=pending;if(statusNode)statusNode.textContent='Gerando demonstração…';renderChatMessages();try{const response=await fetch('/api/tts/synthesize',{method:'POST',headers:{'Content-Type':'application/json','X-Veyro-Request':'1'},body:JSON.stringify({text:clean,profile:profileId,rateAdjustment:rate,pitchAdjustment:pitch})});if(!response.ok){const error=await response.json().catch(()=>({}));throw Error(error.error||'Não foi possível gerar o áudio.');}const blob=await response.blob();if(operation!==speechOperation)return;const url=URL.createObjectURL(blob),audio=new Audio(url),entry={messageId,profileId,status:'ready',audio,url};activeSpeech=entry;audio.playbackRate=speed;audio.onplay=()=>{if(activeSpeech!==entry)return;entry.status='playing';setMascotState('reading');if(statusNode)statusNode.textContent='Reproduzindo demonstração';renderChatMessages();};audio.onpause=()=>{if(activeSpeech!==entry||audio.ended)return;entry.status='paused';setMascotState('idle');if(statusNode)statusNode.textContent='Demonstração pausada';renderChatMessages();};audio.onended=()=>{if(activeSpeech!==entry)return;entry.status='ended';setMascotState('done');if(statusNode)statusNode.textContent='Demonstração concluída';renderChatMessages();};renderChatMessages();if(autoPlay){try{await audio.play();}catch{entry.status='ready';if(statusNode)statusNode.textContent='Áudio pronto. Toque em reproduzir.';feedback('O navegador bloqueou a reprodução automática. Toque em reproduzir para continuar.',true);renderChatMessages();}}}catch(error){if(operation===speechOperation){releaseSpeech();setMascotState('idle');if(statusNode)statusNode.textContent='Falha ao gerar demonstração';feedback(error.message||'O serviço de voz não está disponível.',true);renderChatMessages();}}}
function playSpeech(entry){if(!entry?.audio)return;entry.audio.playbackRate=voiceSpeed;if(entry.audio.ended)entry.audio.currentTime=0;entry.audio.play().catch(()=>feedback('Toque novamente em reproduzir para autorizar o áudio neste navegador.',true));}
function playAssistantMessage(message){if(activeSpeech?.messageId===message.id){if(activeSpeech.status==='loading')return;if(activeSpeech.status==='paused'||activeSpeech.status==='ended'||activeSpeech.status==='ready'){playSpeech(activeSpeech);return;}return;}return requestSpeech(message.text,{messageId:message.id,autoPlay:true});}
const icon=name=>{const svg=document.createElementNS('http://www.w3.org/2000/svg','svg'),use=document.createElementNS('http://www.w3.org/2000/svg','use');use.setAttribute('href','#i-'+name);svg.append(use);svg.setAttribute('aria-hidden','true');return svg;};
function chatModeUI(){document.body.dataset.mode=state.mode;updateWelcome();if(state.mode==='chat'){$('prompt').placeholder='Digite sua mensagem…';$('action-hint').textContent='';$('step-label').textContent='';$('send').setAttribute('aria-label','Enviar mensagem');$('send').replaceChildren(icon('send'));}else document.body.classList.remove('welcome-state');$('voice-input').hidden=state.mode!=='chat';$('voice-language').hidden=state.mode!=='chat';$('translate-input').hidden=state.mode!=='chat';}
function playWelcomeEntrance(){clearTimeout(welcomeEntranceTimer);document.body.classList.remove('welcome-intro','welcome-settled');if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;void $('welcome').offsetWidth;document.body.classList.add('welcome-intro');welcomeEntranceTimer=setTimeout(()=>{document.body.classList.remove('welcome-intro');document.body.classList.add('welcome-settled');},5200);}
function updateWelcome(){const wasVisible=document.body.classList.contains('welcome-state'),welcome=state.mode==='chat'&&!(state.chatMessages?.length);$('welcome').hidden=!welcome;document.body.classList.toggle('welcome-state',welcome);if(welcome&&!wasVisible)playWelcomeEntrance();else if(!welcome&&wasVisible){clearTimeout(welcomeEntranceTimer);document.body.classList.remove('welcome-intro','welcome-settled');}}
async function updateSidebar(){state.conversations=await api('conversations');renderSidebar();}
function renderSidebar(){const root=$('recent-conversations');root.replaceChildren();for(const c of state.conversations||[]){const b=button('',async()=>{if(state.busy)return;await saveChatDraft();await save();await loadProject(c.project_id,{conversationId:c.id});closeSidebar();},'conversation-link');b.append(icon('chat'),el('span',c.title));const time=el('time',new Date(c.updated_at).toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'}));time.dateTime=new Date(c.updated_at).toISOString();b.append(time);b.setAttribute('aria-current',String(c.id===state.conversationId));b.title=c.title;root.append(b);}if(!root.children.length)root.append(el('p','Suas conversas aparecerão aqui.','sidebar-empty'));}
async function openProjectConversation(preferred){await updateSidebar();let c=preferred?state.conversations.find(c=>c.id===preferred&&c.project_id===state.id):state.conversations.find(c=>c.project_id===state.id);if(!c){const created=await api('conversations',{method:'POST',body:{projectId:state.id}});c={id:created.id};await updateSidebar();}const data=await api('conversations/'+c.id);state.conversationId=c.id;state.conversation=data.conversation;state.chatMessages=data.messages;$('older-messages').hidden=!data.hasMore;chatDraftDirty=false;state.mode='chat';$('prompt').value=data.conversation.draft||'';state.chatDraft=$('prompt').value;history.replaceState(null,'','#c-'+c.id);$('empty').hidden=true;$('review').hidden=true;$('result').hidden=true;$('photo-view').hidden=true;$('editor-view').hidden=true;$('chat-view').hidden=false;setStep('chat');modeButtons();renderChatMessages();renderSidebar();resizeText();}
async function newConversation(){if(state.busy)return;await saveChatDraft();await save();const c=await api('conversations',{method:'POST',body:{projectId:state.id}});await openProjectConversation(c.id);closeSidebar();$('prompt').focus();}
function draftChanged(){state.chatDraft=$('prompt').value;chatDraftDirty=true;clearTimeout(chatDraftTimer);chatDraftTimer=setTimeout(()=>handle(saveChatDraft),900);}
async function saveChatDraft(){clearTimeout(chatDraftTimer);if(!chatDraftDirty||!state.conversationId)return;const id=state.conversationId,draft=state.chatDraft;await api('conversations/'+id,{method:'PATCH',body:{draft}});if(state.conversationId===id&&state.chatDraft===draft)chatDraftDirty=false;}
function richText(target,text){target.replaceChildren();for(const line of text.split('\n')){const p=el('div');if(/^[-*] /.test(line))p.className='text-list-item';const value=line.replace(/^[-*] /,'• ');for(const part of value.split(/(\*\*[^*]+\*\*)/g)){if(part.startsWith('**')&&part.endsWith('**'))p.append(el('strong',part.slice(2,-2)));else p.append(document.createTextNode(part));}if(!line)p.append(document.createElement('br'));target.append(p);}}
function renderChatMessages(){const log=$('chat-log'),nearBottom=$('workspace').scrollHeight-$('workspace').scrollTop-$('workspace').clientHeight<180;log.replaceChildren();for(const m of state.chatMessages||[]){const row=el('article',undefined,'chat-message '+m.role),content=el('div',undefined,'chat-message-content');row.dataset.message=m.id;if(m.role==='assistant'){const author=el('div',undefined,'assistant-author'),portrait=el('span',undefined,'mascot-portrait mascot-reply-portrait');portrait.dataset.mascot=selectedMascot;portrait.setAttribute('aria-label',mascotName());author.append(portrait,el('span',mascotName(),'message-author'));if(m.status==='COMPLETE'&&m.text){const active=activeSpeech?.messageId===m.id,listen=button(active&&activeSpeech.status==='loading'?'Gerando áudio…':'Ouvir resposta',()=>playAssistantMessage(m),'message-speech');listen.disabled=active&&activeSpeech.status==='loading';listen.setAttribute('aria-label','Ouvir resposta de '+mascotName());author.append(listen);if(active&&activeSpeech.audio){const toggle=button(activeSpeech.status==='playing'?'Pausar':'Continuar',()=>activeSpeech.status==='playing'?activeSpeech.audio.pause():playSpeech(activeSpeech),'message-speech'),stop=button('Parar',stopSpeech,'message-speech');toggle.setAttribute('aria-label',activeSpeech.status==='playing'?'Pausar leitura':'Continuar leitura');stop.setAttribute('aria-label','Parar leitura');author.append(toggle,stop);}}row.append(author);}else row.append(el('span',m.role==='user'?'Você':'Aviso do sistema','message-author'));const body=el('div',undefined,'message-body');richText(body,m.text|| (m.status==='RUNNING'?'Veyro está pensando…':''));content.append(body);
 for(const a of m.attachments||[]){const link=el('a',a.name,'message-file');link.href='/api/projects/'+state.id+'/assets/'+a.id;link.target='_blank';link.rel='noopener';content.append(link);}
 if(m.tool)content.append(toolCard(m.tool));
 if(m.status==='RUNNING'){const status=el('small',m.text?'Veyro está respondendo…':'Veyro está pensando…','reply-state');status.setAttribute('role','status');content.append(status);}else if(['FAILED','CANCELLED','WAITING'].includes(m.status)){content.append(el('small',m.status==='FAILED'?'Resposta não concluída':m.status==='CANCELLED'?'Resposta interrompida':'Aguardando conexão','reply-state'));const userMessage=[...(state.chatMessages||[])].reverse().find(x=>x.role==='user'&&x.created_at<=m.created_at);if(userMessage&&!m.tool)content.append(button('Tentar novamente',()=>sendChat(userMessage.text,userMessage.attachments?.map(a=>a.id)),'retry-button'));}
 row.append(content);log.append(row);}updateWelcome();if(nearBottom)$('workspace').scrollTop=$('workspace').scrollHeight;}
function toolCard(tool){if(tool.type==='research')return researchCard(tool);const card=el('section',undefined,'chat-tool-card');if(tool.type==='editor'){card.append(icon('video'),el('h3','Edição de vídeo'),el('p',tool.request||'Pedido de edição preparado.'),button('Abrir editor',()=>studioRoute('editor',tool.request||''),'small-button'));return card;}
 card.append(icon('image'),el('h3',tool.needsSource?'Escolha a foto para editar':'Pedido de imagem'),el('p',tool.prompt||''));
 const job=state.photoJobs?.find(j=>j.id===tool.jobId);if(job){card.append(el('small',job.outputs.length+' de '+job.request.count+' imagem(ns) · '+({WAITING:'aguardando conexão',COMPLETE:'prontas para revisar',PARTIAL:'parcial salvo',FAILED:'não concluído',QUEUED:'preparado',RUNNING:'gerando',CANCELLED:'cancelado'}[job.status]||job.status)));const grid=el('div',undefined,'inline-images');for(const o of job.outputs){const a=state.allAssets.find(a=>a.id===o.assetId);if(a){const link=el('a');link.href='/api/projects/'+state.id+'/assets/'+a.id;link.target='_blank';link.rel='noopener';link.append(media(a));grid.append(link);}}card.append(grid);if(state.images&&['WAITING','QUEUED','PARTIAL'].includes(job.status))card.append(button('Gerar '+(job.request.count-job.outputs.length)+' imagem(ns)',async()=>{await processPhoto(job.id);renderChatMessages();},'small-button'));}
 else card.append(el('small',tool.needsSource?'Adicione a foto pelo + e escolha a referência.':'Pedido salvo no Photo Studio.'));
 card.append(button('Ajustar pedido',()=>studioRoute('photo',tool.prompt||''),'small-button'));return card;
}
function updateStreamingBody(message){const row=[...$('chat-log').children].find(el=>el.dataset.message===message.id);if(row)richText(row.querySelector('.message-body'),message.text);else renderChatMessages();const workspace=$('workspace');if(workspace.scrollHeight-workspace.scrollTop-workspace.clientHeight<240)workspace.scrollTop=workspace.scrollHeight;}
async function readChatStream(response,onEvent){if(!response.ok){const e=await response.json();throw Error(e.error||'Não foi possível enviar.');}const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='',terminal=false;try{for(;;){const {value,done}=await reader.read();buffer+=done?decoder.decode():decoder.decode(value,{stream:true});buffer=buffer.replace(/\r/g,'');let boundary;while((boundary=buffer.indexOf('\n\n'))>=0){const block=buffer.slice(0,boundary);buffer=buffer.slice(boundary+2);const event=block.split('\n').find(l=>l.startsWith('event:'))?.slice(6).trim();const data=block.split('\n').filter(l=>l.startsWith('data:')).map(l=>l.slice(5)).join('\n');if(event&&data){const parsed=JSON.parse(data);await onEvent(event,parsed);if(['done','waiting','error','cancelled'].includes(event))terminal=true;}}if(done)break;}if(!terminal)throw Error('A conexão caiu antes de concluir a resposta.');}finally{reader.releaseLock();}}
async function sendChat(text,attachmentIds){if(state.busy||!state.conversationId)return;if(!text&&!state.files.length)throw Error('Escreva uma mensagem ou adicione um arquivo.');await saveChatDraft();await save();const cid=state.conversationId,requestId=crypto.randomUUID(),now=Date.now(),ids=attachmentIds||state.files.map(f=>f.id),assistant={id:requestId,role:'assistant',text:'',status:'RUNNING',created_at:now+1};
 state.chatMessages.push({id:requestId+'-user',role:'user',text,status:'COMPLETE',attachments:state.allAssets.filter(a=>ids.includes(a.id)),created_at:now},assistant);renderChatMessages();$('workspace').scrollTop=$('workspace').scrollHeight;setMascotState('thinking');busy(true);$('new-chat').disabled=true;$('prompt').disabled=true;$('stop-response').hidden=false;$('send').hidden=true;chatController=new AbortController();chatRequestId=requestId;feedback('');
 let accepted=false;
 try{const response=await fetch('/api/conversations/'+cid+'/messages',{method:'POST',headers:{'Content-Type':'application/json','X-Veyro-Request':'1'},body:JSON.stringify({requestId,message:text,attachments:ids,researchMode:state.researchMode||'STANDARD'}),signal:chatController.signal});await readChatStream(response,async(event,data)=>{
  if(event==='status'){accepted=true;$('prompt').value='';state.chatDraft='';chatDraftDirty=false;state.conversation.title=data.title;resizeText();}
  if(event==='research_status'){feedback(({SEARCHING:'Pesquisando…',READING:'Lendo as fontes…',VERIFYING:'Verificando fontes…'})[data.status]||'Preparando pesquisa…');const row=[...$('chat-log').children].find(n=>n.dataset.message===assistant.id);if(row)row.querySelector('.message-body').textContent=$('feedback').textContent;}
  if(event==='token'){if(!assistant.text)setMascotState('speaking');assistant.text+=data.text;updateStreamingBody(assistant);}
  if(event==='notice'){assistant.role=data.role||'notice';assistant.text=data.text;renderChatMessages();}
  if(event==='tool'){assistant.tool=data;renderChatMessages();}
  if(event==='done'){assistant.status='COMPLETE';setMascotState('done');}if(event==='waiting'){assistant.status='WAITING';setMascotState('idle');}if(event==='cancelled'){assistant.status='CANCELLED';setMascotState('idle');}if(event==='error'){assistant.status='FAILED';setMascotState('idle');feedback(data.message,true);}
 });}
 catch(e){assistant.status=e.name==='AbortError'?'CANCELLED':'FAILED';setMascotState('idle');feedback(e.name==='AbortError'?'Resposta interrompida.':e.message||'Não foi possível enviar.',e.name!=='AbortError');if(!accepted){$('prompt').value=text;state.chatDraft=text;chatDraftDirty=true;}}
 finally{chatRequestId=null;chatController=null;busy(false);$('new-chat').disabled=false;$('prompt').disabled=false;$('stop-response').hidden=true;$('send').hidden=false;try{const data=await api('conversations/'+cid);state.chatMessages=data.messages;if(!accepted&&data.messages.some(m=>m.id===requestId)){state.chatDraft=data.conversation.draft;$('prompt').value=state.chatDraft;chatDraftDirty=false;}await refreshDetails();await updateSidebar();}catch{}renderChatMessages();resizeText();if(voiceAutoRead&&assistant.status==='COMPLETE'){const completed=state.chatMessages.find(m=>m.id===requestId&&m.role==='assistant');if(completed)requestSpeech(completed.text,{messageId:completed.id,autoPlay:true});}}
}
async function stopResponse(){if(!chatRequestId)return;const id=chatRequestId;try{await api('conversations/'+state.conversationId+'/cancel',{method:'POST',body:{requestId:id}});}finally{chatController?.abort();}}
function closeSidebar(){document.body.classList.remove('sidebar-open');$('sidebar-overlay').hidden=true;$('sidebar-toggle').setAttribute('aria-expanded','false');$('sidebar').removeAttribute('aria-modal');if(innerWidth<900)$('sidebar').setAttribute('inert','');}
function toggleSidebar(){const mobile=innerWidth<900;if(mobile){const open=!document.body.classList.contains('sidebar-open');document.body.classList.toggle('sidebar-open',open);$('sidebar-overlay').hidden=!open;$('sidebar-toggle').setAttribute('aria-expanded',String(open));if(open){$('sidebar').removeAttribute('inert');$('sidebar').setAttribute('role','dialog');$('sidebar').setAttribute('aria-modal','true');$('sidebar-close').focus();}else closeSidebar();}else{document.body.classList.toggle('sidebar-collapsed');$('sidebar-toggle').setAttribute('aria-expanded',String(!document.body.classList.contains('sidebar-collapsed')));}}
async function loadProfile(){chatProfile=await api('profile');$('profile-name').textContent=chatProfile.name;$('profile-open').setAttribute('aria-label','Abrir perfil de '+chatProfile.name);const avatar=$('profile-avatar');avatar.replaceChildren();if(chatProfile.avatar){const img=el('img');img.src='/api/profile/avatar?v='+chatProfile.updatedAt;img.alt='Foto do perfil';avatar.append(img);}else avatar.append(icon('user'));}
async function profilePanel(){await loadProfile();const root=openPanel('Meu perfil'),name=el('input');name.value=chatProfile.name;name.maxLength=80;name.setAttribute('aria-label','Seu nome');const photo=el('input');photo.type='file';photo.accept='image/png,image/jpeg,image/webp';photo.setAttribute('aria-label','Escolher foto do perfil');photo.onchange=()=>handle(async()=>{const file=photo.files[0];if(!file)return;if(file.size>2*1024*1024)throw Error('Use uma foto de até 2 MB.');const form=new FormData();form.set('file',file);await api('profile/avatar',{method:'POST',body:form});await loadProfile();feedback('Foto do perfil atualizada.');});root.append(el('label','Nome'),name,button('Salvar nome',async()=>{await api('profile',{method:'PUT',body:{name:name.value}});await loadProfile();feedback('Perfil salvo.');}),el('p','Foto do perfil · JPG, PNG ou WebP, até 2 MB.','pending-note'),photo);}
function projectOptions(){const root=openPanel('Conversa e projeto'),title=el('input');title.value=state.conversation?.title||'Nova conversa';title.maxLength=80;title.setAttribute('aria-label','Título da conversa');root.append(title,button('Renomear conversa',async()=>{await api('conversations/'+state.conversationId,{method:'PATCH',body:{title:title.value}});await updateSidebar();state.conversation.title=title.value; $('panel').close();}),button('Vozes do Veyro IA',voiceSettings),button('Trocar projeto',projects),button('Memórias',knowledgeMemories),button('Versões do projeto',versions),button('Atividade e conexão',activity),button('Arquivar conversa',archiveCurrent),button('Excluir conversa',deleteCurrentPanel,'danger-button'));}
function voiceSettings(){const root=openPanel('Vozes do Veyro IA'),intro=el('p','Escolha uma voz compatível com o provedor ativo. Sua seleção e ajustes ficam salvos neste navegador.','review-help'),status=el('p',state.ttsProvider==='pocket'?(state.tts?'Pocket TTS local configurado. A voz Rafael é sintetizada no computador.':'Pocket TTS selecionado, mas o serviço local não respondeu na configuração.'):(state.tts?'Azure Speech configurado. O texto será enviado à Microsoft para sintetizar a voz.':'Azure Speech não configurado. O chat continua funcionando em texto. Configure a chave e a região no servidor.'),'voice-provider-status');status.setAttribute('role','status');const cards=el('div',undefined,'voice-profile-grid');for(const [id,voice]of Object.entries(VEYRO_VOICES)){if((state.ttsProvider==='pocket'&&id!=='rafael')||(state.ttsProvider!=='pocket'&&id==='rafael'))continue;const card=el('article',undefined,'voice-profile-card'+(currentVoiceProfile()===id?' selected':'')),heading=el('div',undefined,'voice-card-heading');heading.append(el('strong',voice.name),el('small',voice.gender));card.append(heading,el('p',voice.description),el('code',voice.voice),button(currentVoiceProfile()===id?'Selecionada':'Selecionar',()=>{selectedVoice=id;try{localStorage.setItem(VOICE_KEY,id);}catch{}voiceSettings();},'voice-select'),button('Ouvir demonstração',()=>requestSpeech('Olá! Esta é uma demonstração da voz '+voice.name+'. A Veyro IA está pronta para ajudar você.',{profileId:id,rate:voiceRate,pitch:voicePitch,speed:voiceSpeed,statusNode:demoStatus,autoPlay:true}),'voice-demo'));cards.append(card);}const demoStatus=el('p','Selecione uma voz e toque em ouvir para testar.','voice-demo-status');demoStatus.id='voice-demo-status';
 const rateLabel=el('label',undefined,'voice-setting'),rateTitle=el('span','Ajuste de velocidade da voz');const rateInput=el('input');rateInput.type='range';rateInput.min='-15';rateInput.max='15';rateInput.step='1';rateInput.value=String(voiceRate);rateInput.disabled=state.ttsProvider==='pocket';const rateValue=el('output',(voiceRate>0?'+':'')+voiceRate+'%');rateLabel.append(rateTitle,rateInput,rateValue);rateInput.oninput=()=>{voiceRate=Number(rateInput.value);rateValue.textContent=(voiceRate>0?'+':'')+voiceRate+'%';try{localStorage.setItem(VOICE_RATE_KEY,String(voiceRate));}catch{}};
 const pitchLabel=el('label',undefined,'voice-setting'),pitchTitle=el('span','Ajuste de tonalidade');const pitchInput=el('input');pitchInput.type='range';pitchInput.min='-6';pitchInput.max='6';pitchInput.step='1';pitchInput.value=String(voicePitch);pitchInput.disabled=state.ttsProvider==='pocket';const pitchValue=el('output',(voicePitch>0?'+':'')+voicePitch+'%');pitchLabel.append(pitchTitle,pitchInput,pitchValue);pitchInput.oninput=()=>{voicePitch=Number(pitchInput.value);pitchValue.textContent=(voicePitch>0?'+':'')+voicePitch+'%';try{localStorage.setItem(VOICE_PITCH_KEY,String(voicePitch));}catch{}};
 const speedLabel=el('label','Velocidade de reprodução','voice-setting'),speed=languageSelect('voice-playback-speed',[['0.75','0,75×'],['0.9','0,9×'],['1','1×'],['1.1','1,1×'],['1.25','1,25×'],['1.5','1,5×']],String(voiceSpeed));speed.onchange=()=>{voiceSpeed=Number(speed.value);try{localStorage.setItem(VOICE_SPEED_KEY,String(voiceSpeed));}catch{}if(activeSpeech?.audio)activeSpeech.audio.playbackRate=voiceSpeed;};speedLabel.append(speed);
 const autoLabel=el('label',undefined,'voice-auto-setting'),auto=el('input');auto.type='checkbox';auto.checked=voiceAutoRead;auto.onchange=()=>{voiceAutoRead=auto.checked;try{localStorage.setItem(VOICE_AUTO_KEY,String(voiceAutoRead));}catch{}renderMascot();};autoLabel.append(auto,el('span','Ler respostas automaticamente (desativado por padrão)'));
 root.append(intro,status,cards,demoStatus,rateLabel,pitchLabel,speedLabel,autoLabel,el('p',state.ttsProvider==='pocket'?'Processamento local: o texto fica no computador. Pocket TTS oferece uma voz pronta em português; os ajustes de tom e prosódia não se aplicam a esse perfil.':'Aviso: o texto enviado para a síntese é processado pelo Azure Speech. A franquia e qualquer cobrança dependem da conta Azure configurada. Evite narrar conteúdo sensível.','voice-privacy'),button('Parar reprodução',stopSpeech,'small-button'));
}
function agentsPanel(){const root=openPanel('Agentes e recursos');for(const [name,status,description]of [['Veyro Core',state.chat?'Modelo configurado':'Aguardando modelo','Conversa, contexto e preparação de pedidos.'],['Photo Studio',state.images?'Gerador configurado':'Aguardando gerador','Pedidos de criação e edição de imagens.'],['Editor','Controles disponíveis','Cortes, velocidade e montagem de vídeos enviados.'],['Qualidade','Verificação básica','Valida parâmetros. A avaliação visual automática ainda não está conectada.']]){const card=el('article',undefined,'memory-card');card.append(el('strong',name),el('small',status),el('p',description));root.append(card);}}
function languageSelect(id,entries,selected){const s=el('select');s.id=id;for(const [value,label]of entries){const option=el('option',label);option.value=value;s.append(option);}s.value=selected;return s;}
async function translatePanel(){const root=openPanel('Traduzir texto'),source=languageSelect('translate-source',[['auto','Detectar idioma'],['pt','Português'],['en','Inglês'],['es','Espanhol'],['fr','Francês'],['de','Alemão'],['it','Italiano'],['ja','Japonês'],['zh','Chinês']],'auto'),target=languageSelect('translate-target',[['en','Inglês'],['pt','Português'],['es','Espanhol'],['fr','Francês'],['de','Alemão'],['it','Italiano'],['ja','Japonês'],['zh','Chinês']],'en'),input=el('textarea'),output=el('textarea');input.value=$('prompt').value;input.rows=4;input.maxLength=8000;input.placeholder='Texto para traduzir';input.setAttribute('aria-label','Texto para traduzir');output.rows=4;output.readOnly=true;output.placeholder='A tradução aparecerá aqui';output.setAttribute('aria-label','Texto traduzido');const translate=button('Traduzir',async()=>{translate.disabled=true;output.value='Traduzindo localmente com Qwen…';try{const result=await api('translate',{method:'POST',body:{text:input.value,sourceLanguage:source.value,targetLanguage:target.value}});output.value=result.translation;feedback('Idioma detectado: '+result.detectedLanguage.toUpperCase());}finally{translate.disabled=false;}});root.append(el('label','Idioma de origem'),source,el('label','Traduzir para'),target,input,translate,output,button('Usar tradução no chat',()=>{if(!output.value)throw Error('Traduza o texto primeiro.');$('prompt').value=output.value;$('prompt').dispatchEvent(new Event('input'));$('panel').close();$('prompt').focus();feedback('Tradução inserida. Revise o texto antes de enviar.');}));}
async function toggleRecording(){if(recorder?.state==='recording'){recorder.stop();return;}if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)throw Error('A gravação de áudio não está disponível neste navegador.');recordingStream=await navigator.mediaDevices.getUserMedia({audio:true});const mime=['audio/webm;codecs=opus','audio/webm','audio/mp4'].find(type=>MediaRecorder.isTypeSupported(type))||'';recorder=new MediaRecorder(recordingStream,mime?{mimeType:mime}:undefined);const chunks=[];recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};recorder.onstart=()=>{$('voice-input').classList.add('recording');$('voice-input').setAttribute('aria-label','Concluir gravação');feedback('Gravando… toque no microfone para concluir. Limite de 120 segundos.');recordingTimer=setTimeout(()=>recorder?.state==='recording'&&recorder.stop(),120000);};recorder.onerror=()=>feedback('Falha ao gravar o áudio.',true);recorder.onstop=async()=>{clearTimeout(recordingTimer);$('voice-input').classList.remove('recording');$('voice-input').disabled=true;feedback('Transcrevendo no computador…');try{const blob=new Blob(chunks,{type:recorder.mimeType||'audio/webm'});if(blob.size>15*1024*1024)throw Error('O áudio passou do limite de 15 MB.');const form=new FormData();form.set('file',blob,'recording.'+(blob.type.includes('mp4')?'mp4':'webm'));form.set('language',$('voice-language').value);const result=await api('speech/transcribe',{method:'POST',body:form});const current=$('prompt').value;$('prompt').value+=(current?' ':'')+result.text;$('prompt').dispatchEvent(new Event('input'));resizeText();$('prompt').focus();feedback('Texto reconhecido. Revise ou edite antes de enviar.');}catch(e){feedback(e.message||'Não foi possível transcrever.',true);}finally{recordingStream?.getTracks().forEach(track=>track.stop());recordingStream=null;recorder=null;$('voice-input').disabled=false;$('voice-input').setAttribute('aria-label','Gravar mensagem de voz');}};recorder.start();}
function initChat(){state.chatMessages=[];state.conversations=[];state.conversationId=null;state.chatDraft='';$('new-chat').onclick=()=>handle(newConversation);$('home-chat').onclick=()=>handle(()=>changeMode('chat'));$('sidebar-toggle').onclick=toggleSidebar;$('sidebar-overlay').onclick=closeSidebar;$('sidebar-close').onclick=closeSidebar;
 renderMascot();setMascotState('idle');$('mascot-open').onclick=openMascotPicker;$('mascot-close').onclick=()=>$('mascot-picker').close();$('mascot-picker').onclick=e=>{if(e.target===$('mascot-picker'))$('mascot-picker').close();};for(const option of document.querySelectorAll('[data-mascot-choice]'))option.onclick=()=>chooseMascot(option.dataset.mascotChoice);$('mascot-confirm').onclick=()=>{$('mascot-picker').close();$('prompt').focus();};$('voice-toggle').onclick=()=>{voiceAutoRead=!voiceAutoRead;try{localStorage.setItem(VOICE_AUTO_KEY,String(voiceAutoRead));}catch{}renderMascot();};if(!readPreference(MASCOT_KEY,''))setTimeout(()=>{if(!$('mascot-picker').open)openMascotPicker();},350);
 $('nav-images').onclick=()=>handle(async()=>{await changeMode('photo');closeSidebar();});$('nav-videos').onclick=()=>{const root=openPanel('Vídeos');root.append(button('Planejar um vídeo',async()=>{await changeMode('create');$('panel').close();closeSidebar();}),button('Editar um vídeo enviado',async()=>{await changeMode('editor');$('panel').close();closeSidebar();}));};$('nav-agents').onclick=agentsPanel;$('profile-open').onclick=()=>handle(profilePanel);$('project-options').onclick=projectOptions;$('stop-response').onclick=()=>handle(stopResponse);
 for(const b of document.querySelectorAll('[data-suggestion]'))b.onclick=()=>{$('prompt').value=b.dataset.suggestion;draftChanged();resizeText();$('prompt').focus();};for(const b of document.querySelectorAll('[data-action]'))b.onclick=()=>handle(()=>changeMode(b.dataset.action==='plan'?'create':'editor'));
 $('voice-input').onclick=()=>handle(toggleRecording);$('translate-input').onclick=()=>handle(translatePanel);
 $('prompt').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing&&innerWidth>=900){e.preventDefault();$('composer').requestSubmit();}});
 document.addEventListener('keydown',e=>{if(e.key==='Escape')closeSidebar();if(e.key==='Tab'&&innerWidth<900&&document.body.classList.contains('sidebar-open')){const nodes=[...$('sidebar').querySelectorAll('button:not([disabled])')],first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
 const responsive=()=>{if(innerWidth>=900){$('sidebar').removeAttribute('inert');$('sidebar').removeAttribute('aria-modal');$('sidebar').removeAttribute('role');$('sidebar-overlay').hidden=true;}else if(!document.body.classList.contains('sidebar-open'))closeSidebar();};window.addEventListener('resize',responsive);responsive();handle(loadProfile);
}
