'use strict';
let editorUndo=[],editorRedo=[],previewVideo=null,exportAbort=null,exportUrl=null;
const emptyPhoto=()=>({prompt:'',operation:'generate',count:1,size:'1024x1024',sourceId:'',sceneId:'',preserve:''});
const emptyEditor=()=>({clips:[],format:'original',resolution:'720',mode:'ASSISTED',intensity:'LOW',request:''});
function studioLoad(){state.photo={...emptyPhoto(),...state.photo};state.editor={...emptyEditor(),...state.editor};editorUndo=[];editorRedo=[];$('photo-view').hidden=true;$('editor-view').hidden=true;$('export-result').replaceChildren();$('export-status').textContent='';if(exportUrl){URL.revokeObjectURL(exportUrl);exportUrl=null;}}
function studioComposer(){const photo=state.mode==='photo';state.step=photo?'photo':'editor';for(const id of ['formats','durations','back','review-choice','format-summary'])$(id).hidden=true;$('step-label').textContent=photo?'IMAGEM INDEPENDENTE OU POR CENA':'EDIÇÃO DO VÍDEO';$('prompt').placeholder=photo?'Descreva a imagem que quer criar…':'Ex.: corta os 3 primeiros segundos do primeiro trecho';$('action-hint').textContent=photo?(state.images?'Criar imagens':'Salvar pedido de imagem'):'Aplicar comando de corte';$('send').setAttribute('aria-label',photo?'Enviar pedido de imagem':'Aplicar comando de edição');$('attachments').hidden=!state.files.length;}
function studioOpen(){for(const id of ['chat-view','empty','review','result'])$(id).hidden=true;$('photo-view').hidden=state.mode!=='photo';$('editor-view').hidden=state.mode!=='editor';$('prompt').value=state.mode==='photo'?state.photo.prompt:state.editor.request;studioComposer();studioRender();modeButtons();resizeText();$('workspace').scrollTop=0;}
async function studioRoute(mode,prompt){await changeMode(mode);if(mode==='photo'){state.photo.prompt=prompt;const lower=prompt.toLowerCase();state.photo.operation='generate';const count=lower.match(/\b([1-5])\s+(?:foto|image|varia)/);if(count)state.photo.count=Number(count[1]);}else state.editor.request=prompt;$('prompt').value=prompt;studioRender();changed();feedback(mode==='photo'?'Pedido direcionado ao Photo Studio. Confira as opções e envie.':'Pedido direcionado ao editor. Adicione um trecho e confira o comando.');resizeText();}
function fillSelect(node,items,value){node.replaceChildren();for(const [v,text]of items){const o=el('option',text);o.value=v;node.append(o);}node.value=value;}
function studioRender(){if(state.mode==='photo')renderPhoto();if(state.mode==='editor')renderEditor();}
function renderPhoto(){const p=state.photo;$('photo-operation').value=p.operation;$('photo-count').value=p.count;$('photo-size').value=p.size;$('photo-preserve').value=p.preserve;
 fillSelect($('photo-scene'),[['','Imagem independente'],...state.scenes.map((s,i)=>[s.id,'Cena '+(i+1)])],p.sceneId);
 fillSelect($('photo-source'),[['','Sem referência'],...state.allAssets.filter(a=>/^image\/(png|jpeg|webp)$/.test(a.mime)).map(a=>[a.id,a.name])],p.sourceId);
 $('photo-connection').textContent=state.images?'Gerador local SDXL-Lightning conectado pelo ComfyUI. A criação roda no seu computador, sem API paga.':'Instale o ComfyUI e o checkpoint SDXL-Lightning; depois habilite o gerador local em .env.';
 const gallery=$('photo-gallery');gallery.replaceChildren();for(const a of state.allAssets.filter(a=>a.metadata?.photoJobId)){const card=el('article',undefined,'photo-card');card.append(media(a),el('p',a.name),el('small','Gerada por IA · confira os detalhes'));const link=el('a','Abrir imagem');link.href='/api/'+route('assets/'+a.id);link.target='_blank';link.rel='noopener';card.append(link,button(state.files.some(f=>f.id===a.id)?'Referência adicionada ✓':'Usar como referência',()=>{if(state.files.some(f=>f.id===a.id))return;if(state.files.length>=12)throw Error('Remova uma referência antes de adicionar outra.');state.files.push(a);renderFiles();changed();renderPhoto();},'small-button'));gallery.append(card);}
 const list=$('photo-jobs');list.replaceChildren();const names={WAITING:'Aguardando conexão',QUEUED:'Pronto para gerar',RUNNING:'Gerando uma imagem',PARTIAL:'Resultado parcial salvo',COMPLETE:'Imagens prontas para revisão',FAILED:'Não concluído',CANCELLED:'Cancelado'};
 for(const j of state.photoJobs){const card=el('details',undefined,'original-request');card.append(el('summary',(names[j.status]||j.status)+' · '+j.outputs.length+'/'+j.request.count),el('p',j.request.prompt),el('p',j.request.sceneText?'Referência de cena: '+j.request.sceneText:'Imagem independente'));if(j.error)card.append(el('p',j.error,'error'));if(['QUEUED','PARTIAL','WAITING'].includes(j.status)&&state.images)card.append(button('Continuar este pedido',()=>processPhoto(j.id),'small-button'));if(['WAITING','QUEUED','PARTIAL','RUNNING'].includes(j.status))card.append(button('Cancelar pedido',async()=>{await api(route('photo-jobs/'+j.id+'/cancel'),{method:'POST',body:{}});await refreshDetails();},'small-button'));list.append(card);}if(!state.photoJobs.length)list.append(el('p','Seus pedidos de imagem aparecerão aqui.','pending-note'));
}
async function submitPhoto(){state.photo.prompt=$('prompt').value.trim();if(!state.photo.prompt)throw Error('Descreva a imagem que quer criar.');if(state.photo.operation!=='generate')throw Error('Edição e aprimoramento ainda não estão disponíveis.');await save();busy(true);try{const job=await api(route('photo-jobs'),{method:'POST',body:{id:crypto.randomUUID(),settings:state.photo}});await refreshDetails();if(state.images)await processPhoto(job.id);else feedback('Pedido de imagem salvo. A geração aguarda a conexão com IA.');}finally{busy(false);}}
async function processPhoto(id){busy(true);try{for(let i=0;i<5;i++){feedback('Gerando imagem… Os resultados serão salvos separadamente.');const job=await api(route('photo-jobs/'+id+'/run'),{method:'POST',body:{}});await refreshDetails();if(job.status!=='PARTIAL'){feedback(job.status==='COMPLETE'?'Imagens salvas. Confira o resultado antes de usar.':job.error||'Pedido '+job.status.toLowerCase(),job.status==='FAILED');break;}}}finally{busy(false);}}
function editorLength(clips=state.editor.clips){return clips.reduce((n,c)=>n+(c.end-c.start)/c.speed,0);}
function editTimeline(fn){if(state.busy)throw Error('Aguarde o processamento terminar.');const before=structuredClone(state.editor);fn();const total=editorLength();if(state.editor.clips.length>30||total>30.01||state.editor.clips.some(c=>c.end<=c.start||c.start<0)){state.editor=before;throw Error('Use trechos válidos e uma montagem de até 30 segundos.');}editorUndo.push(before);if(editorUndo.length>40)editorUndo.shift();editorRedo=[];stopClipPreview();changed();renderEditor();}
function renderEditor(){const e=state.editor;fillSelect($('editor-source'),[['','Escolha um vídeo salvo'],...state.allAssets.filter(a=>a.mime.startsWith('video/')).map(a=>[a.id,a.name])],$('editor-source').value);$('editor-format').value=e.format;$('editor-resolution').value=e.resolution;$('editor-mode-setting').value=e.mode;$('editor-intensity').value=e.intensity;$('editor-undo').disabled=!editorUndo.length;$('editor-redo').disabled=!editorRedo.length;$('editor-total').textContent=editorLength().toFixed(2)+' s / 30 s';const root=$('timeline');root.replaceChildren();
 for(const [index,c]of e.clips.entries()){const a=state.allAssets.find(a=>a.id===c.assetId),card=el('article',undefined,'scene-card'),head=el('div',undefined,'scene-heading');head.append(el('h2','Trecho '+(index+1)),el('span',((c.end-c.start)/c.speed).toFixed(2)+' s'));card.append(head,el('p',a?.name||'Arquivo indisponível','pending-note'));const grid=el('div',undefined,'studio-grid');for(const [key,label]of [['start','Início (s)'],['end','Fim (s)']]){const l=el('label',label),input=el('input');input.type='number';input.min=0;input.step=.01;input.value=c[key];input.onchange=()=>handle(()=>{const value=Number(input.value);if(!Number.isFinite(value))throw Error('Informe um tempo válido.');if(key==='end'&&a?.metadata?.duration&&value>a.metadata.duration+0.05)throw Error('O fim ultrapassa a duração do vídeo.');editTimeline(()=>{state.editor.clips[index][key]=value;});});l.append(input);grid.append(l);}const label=el('label','Velocidade'),select=el('select');fillSelect(select,[.5,.75,1,1.25,1.5,2].map(v=>[String(v),v+'×']),String(c.speed));select.onchange=()=>handle(()=>editTimeline(()=>{state.editor.clips[index].speed=Number(select.value);}));label.append(select);grid.append(label);card.append(grid);const actions=el('div',undefined,'scene-tools');actions.append(button('▶ Ver trecho',()=>previewClip(c),'small-button'),button('Dividir ao meio',()=>editTimeline(()=>{const middle=(c.start+c.end)/2;state.editor.clips.splice(index,1,{...c,end:middle},{...c,id:crypto.randomUUID(),start:middle});}),'small-button'));if(index)actions.append(button('↑ Mover',()=>editTimeline(()=>{[e.clips[index-1],e.clips[index]]=[e.clips[index],e.clips[index-1]];}),'small-button'));actions.append(button('Remover',()=>editTimeline(()=>e.clips.splice(index,1)),'small-button'));card.append(actions);root.append(card);}
 if(!e.clips.length)root.append(el('p','Adicione um vídeo à timeline para começar.','pending-note'));$('editor-export').disabled=state.busy||!e.clips.length;
}
function stopClipPreview(){if(previewVideo){previewVideo.pause();previewVideo.removeAttribute('src');previewVideo.load();previewVideo=null;}if($('clip-preview'))$('clip-preview').replaceChildren();}
async function sourceDuration(asset){if(asset.metadata?.duration)return asset.metadata.duration;return new Promise((resolve,reject)=>{const v=media(asset),timer=setTimeout(()=>{v.removeAttribute('src');v.load();reject(Error('Não foi possível ler a duração. Tente outro arquivo.'));},10000);v.onloadedmetadata=()=>{clearTimeout(timer);const d=v.duration;v.removeAttribute('src');v.load();Number.isFinite(d)&&d>0?resolve(d):reject(Error('Duração de vídeo inválida.'));};v.onerror=()=>{clearTimeout(timer);reject(Error('O navegador não conseguiu abrir este vídeo.'));};});}
async function addClip(){const a=state.allAssets.find(a=>a.id===$('editor-source').value);if(!a)throw Error('Escolha um vídeo ou adicione um arquivo pelo +.');const duration=await sourceDuration(a),remaining=30-editorLength();if(remaining<.1)throw Error('A montagem já tem 30 segundos.');editTimeline(()=>state.editor.clips.push({id:crypto.randomUUID(),assetId:a.id,start:0,end:Math.min(duration,remaining),speed:1}));}
async function previewClip(c){stopClipPreview();const a=state.allAssets.find(a=>a.id===c.assetId);if(!a)throw Error('Arquivo não encontrado.');const v=media(a,true);previewVideo=v;$('clip-preview').append(v,el('p','Prévia do trecho selecionado · sem áudio','pending-note'));v.playbackRate=c.speed;v.onloadedmetadata=()=>{v.currentTime=c.start;};v.onseeked=()=>{v.onseeked=null;v.play().catch(()=>feedback('Toque no vídeo para iniciar a prévia.'));};v.ontimeupdate=()=>{if(v.currentTime>=c.end)v.pause();};v.onerror=()=>feedback('O navegador não conseguiu reproduzir esse arquivo.',true);}
async function editorCommand(text){state.editor.request=text;changed();await save();const match=text.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().match(/^(?:corta|corte|remova|remove)\s+(?:os\s+)?(\d+(?:[.,]\d+)?)\s+(?:primeiros\s+segundos|segundos\s+(?:iniciais|do inicio))(?:\s+(?:do\s+)?(?:video|primeiro trecho))?[.!]?$/);if(!match)throw Error('A interpretação livre pela IA ainda não está conectada. Use os controles ou “Corta os 3 primeiros segundos”. O pedido foi salvo.');if(!state.editor.clips.length)throw Error('Adicione um vídeo à timeline antes de cortar.');const seconds=Number(match[1].replace(',','.'));if(seconds<=0)throw Error('Informe um corte maior que zero.');editTimeline(()=>{state.editor.clips[0].start+=seconds;});await save();feedback('Corte aplicado ao primeiro trecho. O arquivo original foi preservado.');}
async function exportEditor(){
 if(!state.editor.clips.length)throw Error('Adicione trechos antes de exportar.');
 const canvas=$('export-canvas');if(!canvas.captureStream||!window.MediaRecorder)throw Error('Este navegador não oferece exportação local. A montagem está salva; tente abrir no Chrome atualizado.');
 const mime=['video/webm;codecs=vp9','video/webm;codecs=vp8','video/webm','video/mp4'].find(m=>MediaRecorder.isTypeSupported(m));if(!mime)throw Error('Não há um formato de exportação compatível neste navegador.');
 await save();stopClipPreview();const edit=structuredClone(state.editor),pid=state.id,controller=new AbortController();exportAbort=controller;busy(true);$('export-cancel').hidden=false;canvas.hidden=false;$('export-result').replaceChildren();$('export-status').textContent='Preparando os arquivos…';let recorder,stream,v,animation,watchdog,stopReason=null;const chunks=[];
 try{
  v=document.createElement('video');v.muted=true;v.playsInline=true;v.preload='auto';v.className='export-source';$('editor-view').append(v);
  const event=(name,action,timeout=15000)=>new Promise((resolve,reject)=>{const done=fn=>value=>{clearTimeout(timer);v.removeEventListener(name,ok);v.removeEventListener('error',bad);controller.signal.removeEventListener('abort',cancel);fn(value);};const ok=done(resolve),bad=done(()=>reject(Error('O navegador não conseguiu decodificar um trecho.'))),cancel=done(()=>reject(Error('Exportação cancelada.')));const timer=setTimeout(done(()=>reject(Error('Um trecho demorou demais para carregar.'))),timeout);v.addEventListener(name,ok,{once:true});v.addEventListener('error',bad,{once:true});controller.signal.addEventListener('abort',cancel,{once:true});action();});
  const load=async c=>{if(controller.signal.aborted)throw Error('Exportação cancelada.');await event('loadeddata',()=>{v.src='/api/projects/'+pid+'/assets/'+c.assetId;v.load();});if(c.end>v.duration+.05)throw Error('Um trecho ultrapassa o final do arquivo.');if(Math.abs(v.currentTime-c.start)>.001)await event('seeked',()=>{v.currentTime=Math.min(c.start,v.duration-.001);});v.playbackRate=c.speed;};
  await load(edit.clips[0]);const small=Number(edit.resolution);let ratio=edit.format==='vertical'?9/16:edit.format==='horizontal'?16/9:edit.format==='square'?1:v.videoWidth/v.videoHeight;if(!Number.isFinite(ratio)||ratio<=0)throw Error('Não foi possível ler as dimensões do vídeo.');canvas.width=Math.round((ratio>=1?small*ratio:small)/2)*2;canvas.height=Math.round((ratio>=1?small:small/ratio)/2)*2;if(Math.max(canvas.width,canvas.height)>1920){const scale=1920/Math.max(canvas.width,canvas.height);canvas.width=Math.round(canvas.width*scale/2)*2;canvas.height=Math.round(canvas.height*scale/2)*2;}
  const ctx=canvas.getContext('2d',{alpha:false}),draw=()=>{ctx.fillStyle='#000';ctx.fillRect(0,0,canvas.width,canvas.height);const fit=Math.min(canvas.width/v.videoWidth,canvas.height/v.videoHeight),w=v.videoWidth*fit,h=v.videoHeight*fit;ctx.drawImage(v,(canvas.width-w)/2,(canvas.height-h)/2,w,h);};draw();
  stream=canvas.captureStream(30);recorder=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:3000000});recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};recorder.onerror=()=>{stopReason='Falha do codificador do navegador.';controller.abort();};
  const stopped=new Promise(resolve=>recorder.onstop=resolve);recorder.start(500);recorder.pause();let elapsed=0;const total=editorLength(edit.clips);
  for(let i=0;i<edit.clips.length;i++){
   const clip=edit.clips[i];if(i)await load(clip);draw();
   await new Promise((resolve,reject)=>{let settled=false;const finish=error=>{if(settled)return;settled=true;clearTimeout(watchdog);cancelAnimationFrame(animation);v.pause();v.onwaiting=null;v.onplaying=null;controller.signal.removeEventListener('abort',abort);if(recorder.state==='recording')recorder.pause();error?reject(error):resolve();};const abort=()=>finish(Error(stopReason||'Exportação cancelada.'));controller.signal.addEventListener('abort',abort,{once:true});if(controller.signal.aborted){abort();return;}watchdog=setTimeout(()=>finish(Error('O aparelho demorou demais para processar este trecho. Tente 360p.')),Math.max(20000,(clip.end-clip.start)/clip.speed*4000));
    const frame=()=>{if(v.readyState>=2)draw();const passed=Math.max(0,(v.currentTime-clip.start)/clip.speed);$('export-status').textContent='Exportando '+Math.min(100,Math.round((elapsed+passed)/total*100))+'% · trecho '+(i+1)+'/'+edit.clips.length;if(v.currentTime>=clip.end-.02||v.ended){finish();return;}animation=requestAnimationFrame(frame);};
    v.onwaiting=()=>{if(recorder.state==='recording')recorder.pause();};v.onplaying=()=>{if(recorder.state==='paused')recorder.resume();};v.play().then(()=>{if(recorder.state==='paused')recorder.resume();animation=requestAnimationFrame(frame);}).catch(()=>finish(Error('Toque novamente em Exportar para permitir a reprodução.')));
   });elapsed+=(clip.end-clip.start)/clip.speed;
  }
  recorder.stop();await stopped;if(controller.signal.aborted)throw Error('Exportação cancelada.');const blob=new Blob(chunks,{type:recorder.mimeType});if(blob.size<1000)throw Error('O navegador não produziu um vídeo válido.');if(exportUrl)URL.revokeObjectURL(exportUrl);exportUrl=URL.createObjectURL(blob);const extension=mime.includes('mp4')?'mp4':'webm',name='Veyro-montagem.'+extension,link=el('a','Baixar montagem ('+extension.toUpperCase()+')');link.href=exportUrl;link.download=name;link.className='text-button';const result=el('video');result.src=exportUrl;result.controls=true;result.muted=true;result.playsInline=true;$('export-result').append(result,link);$('export-status').textContent='Montagem exportada. Confira os cortes e a fluidez antes de usar.';
  if(blob.size<=25*1024*1024){const form=new FormData();form.set('file',new File([blob],name,{type:extension==='mp4'?'video/mp4':'video/webm'}));form.set('metadata',JSON.stringify({width:canvas.width,height:canvas.height,duration:total}));try{const a=await api('projects/'+pid+'/assets',{method:'POST',body:form});if(state.id===pid)state.allAssets.push(a);$('export-status').textContent+=' Uma cópia foi salva no projeto.';}catch{$('export-status').textContent+=' Não foi possível salvar na conta; o download está disponível.';}}
 }finally{clearTimeout(watchdog);cancelAnimationFrame(animation);if(recorder&&recorder.state!=='inactive')recorder.stop();if(stream)for(const track of stream.getTracks())track.stop();if(v){v.pause();v.removeAttribute('src');v.load();v.remove();}canvas.hidden=true;exportAbort=null;$('export-cancel').hidden=true;busy(false);renderEditor();}
}
function initStudio(){
 for(const m of ['photo','editor'])$(m+'-mode').onclick=()=>handle(()=>changeMode(m));
 for(const [id,key]of [['photo-operation','operation'],['photo-count','count'],['photo-size','size'],['photo-source','sourceId'],['photo-scene','sceneId'],['photo-preserve','preserve']])$(id).onchange=()=>{state.photo[key]=key==='count'?Number($(id).value):$(id).value;changed();};
 for(const [id,key]of [['editor-format','format'],['editor-resolution','resolution'],['editor-mode-setting','mode'],['editor-intensity','intensity']])$(id).onchange=()=>handle(()=>editTimeline(()=>{state.editor[key]=$(id).value;}));
 $('clip-add').onclick=()=>handle(addClip);$('editor-undo').onclick=()=>handle(()=>{if(state.busy||!editorUndo.length)return;editorRedo.push(structuredClone(state.editor));state.editor=editorUndo.pop();stopClipPreview();changed();renderEditor();});$('editor-redo').onclick=()=>handle(()=>{if(state.busy||!editorRedo.length)return;editorUndo.push(structuredClone(state.editor));state.editor=editorRedo.pop();stopClipPreview();changed();renderEditor();});
 $('editor-export').onclick=()=>handle(exportEditor);$('export-cancel').onclick=()=>exportAbort?.abort();document.addEventListener('visibilitychange',()=>{if(document.hidden&&exportAbort)exportAbort.abort();});
}
