import test from 'node:test';
import assert from 'node:assert/strict';
import {setup} from './helpers.mjs';
import worker from '../src/api/router.js';
import {cleanState,validateProposal} from '../src/core/domain.js';

async function request(env,path,{user='alice',method='GET',body,origin='https://veyro.test'}={}){const headers={'oai-authenticated-user-id':user,'X-Veyro-Request':'1',origin};if(body&&!(body instanceof FormData))headers['content-type']='application/json';const res=await worker.fetch(new Request('https://veyro.test/api/'+path,{method,headers,body:body?(body instanceof FormData?body:JSON.stringify(body)):undefined}),env);return {status:res.status,data:(res.headers.get('content-type')||'').includes('json')?await res.json():await res.arrayBuffer()};}
async function project(env,title='História'){const r=await request(env,'projects',{method:'POST',body:{title}});assert.equal(r.status,201);return r.data.id;}
test('projects enforce ownership, reject cross-origin changes and persist after reads',async()=>{const env=setup(),id=await project(env);assert.equal((await request(env,'projects/'+id,{user:'bob'})).status,404);assert.equal((await request(env,'projects',{method:'POST',body:{title:'bad'},origin:'https://evil.test'})).status,403);assert.equal((await request(env,'projects',{user:''})).status,401);assert.equal((await request(env,'projects/'+id)).data.project.title,'História');});
test('revision conflicts preserve changes and restoration preserves the current version',async()=>{const env=setup(),id=await project(env),url='projects/'+id;const first=cleanState({original:'Primeiro',duration:10,scenes:[{id:'a',text:'Cena inicial',seconds:10}]});assert.equal((await request(env,url,{method:'PUT',body:{revision:0,state:first}})).status,200);assert.equal((await request(env,url,{method:'PUT',body:{revision:0,state:{}}})).status,409);const second={...first,original:'Segundo'};await request(env,url,{method:'PUT',body:{revision:1,state:second}});let data=(await request(env,url)).data;const old=data.versions.find(v=>JSON.parse(env.sqlite.prepare('SELECT state FROM versions WHERE id=?').get(v.id).state).original==='Primeiro');assert.ok(old);assert.equal((await request(env,url+'/restore',{method:'POST',body:{id:old.id,revision:2}})).status,200);data=(await request(env,url)).data;assert.equal(data.project.state.original,'Primeiro');assert.equal(data.project.revision,3);assert.ok(data.versions.some(v=>v.label==='Antes de restaurar'));});
test('project memory is isolated; global preferences are only visible to their owner; forget works',async()=>{const env=setup(),a=await project(env),b=await project(env);const local=await request(env,'projects/'+a+'/memories',{method:'POST',body:{text:'personagem Ana',scope:'project'}});await request(env,'projects/'+a+'/memories',{method:'POST',body:{text:'estilo realista',scope:'global'}});assert.equal((await request(env,'projects/'+a)).data.memories.length,2);assert.equal((await request(env,'projects/'+b)).data.memories.length,1);assert.equal((await request(env,'projects/'+b,{user:'bob'})).status,404);await request(env,'projects/'+a+'/memories',{method:'DELETE',body:{id:local.data.id}});assert.equal((await request(env,'projects/'+a)).data.memories.length,1);});
test('no API key stores a pending request without inventing AI responses; explicit memory works offline',async()=>{const env=setup(),id=await project(env),url='projects/'+id;const req={text:'Crie uma aventura',mode:'chat',requestId:crypto.randomUUID()};await request(env,url+'/chat',{method:'POST',body:req});await request(env,url+'/chat',{method:'POST',body:req});let d=(await request(env,url)).data;assert.equal(d.runs.length,1);assert.equal(d.runs[0].status,'WAITING');assert.equal(d.messages.filter(m=>m.role==='assistant').length,0);assert.equal(d.messages.filter(m=>m.role==='user').length,1);await request(env,url+'/chat',{method:'POST',body:{text:'Lembre: use cenário medieval',mode:'chat',requestId:crypto.randomUUID()}});d=(await request(env,url)).data;assert.equal(d.memories[0].text,'use cenário medieval');});
test('uploaded bytes persist and references cannot be borrowed across projects',async()=>{const env=setup(),a=await project(env),b=await project(env);const form=new FormData();form.append('file',new File([new Uint8Array([1,2,3])],'imagem.png',{type:'image/png'}));const up=await request(env,'projects/'+a+'/assets',{method:'POST',body:form});assert.equal(up.status,201);const aid=up.data.id;assert.equal((await request(env,'projects/'+a+'/assets/'+aid)).data.byteLength,3);assert.equal((await request(env,'projects/'+b+'/assets/'+aid)).status,404);assert.equal((await request(env,'projects/'+b,{method:'PUT',body:{revision:0,state:{fileIds:[aid]}}})).status,400);});
test('quality gate rejects duration mismatch and all mutations of protected scenes',()=>{const state=cleanState({duration:10,scenes:[{id:'a',text:'Preservar',seconds:10,locked:true}]});assert.throws(()=>cleanState({...state,scenes:[{id:'a',text:'X',seconds:5}]}));for(const change of [{text:'Outra'},{seconds:9},{locked:false}])assert.throws(()=>validateProposal({reply:'Proposta',scenes:[{...state.scenes[0],...change}]},state));});
test('local model provider handles core proposals and only applies a reviewed proposal',async()=>{const env=setup(),id=await project(env),url='projects/'+id;await request(env,url,{method:'PUT',body:{revision:0,state:{duration:10,original:'Viagem',scenes:[{id:'a',text:'Antes',seconds:10}]}}});Object.assign(env,{MODEL_PROVIDER:'local',MODEL_BASE_URL:'http://127.0.0.1:11434/v1',MODEL_NAME:'llama3.1:8b',VEYRO_CHAT_ENABLED:'true'});const originalFetch=globalThis.fetch;let captured;globalThis.fetch=async(_,o)=>{captured=JSON.parse(o.body);return new Response(`data: ${JSON.stringify({choices:[{delta:{content:JSON.stringify({reply:'Aqui está uma proposta.',scenes:[{id:'a',text:'Depois',seconds:10,locked:false}],warnings:[],tool:'none'})}}]})}\n\ndata: [DONE]\n\n`);};try{await request(env,url+'/chat',{method:'POST',body:{text:'Melhore',mode:'revise',requestId:crypto.randomUUID()}});}finally{globalThis.fetch=originalFetch;}const d=(await request(env,url)).data;assert.equal(d.runs[0].status,'COMPLETE');assert.equal(d.project.state.scenes[0].text,'Antes');assert.equal(captured.model,'llama3.1:8b');assert.ok(captured.messages[0].content.includes('Veyro IA'));assert.equal((await request(env,url+'/apply',{method:'POST',body:{id:d.runs[0].id,revision:1}})).status,200);assert.equal((await request(env,url)).data.project.state.scenes[0].text,'Depois');});
