import test from 'node:test';
import assert from 'node:assert/strict';
import {setup} from './helpers.mjs';
import {database} from '../src/storage/db.js';
import worker from '../src/api/router.js';
import {basicMemoryIntent,saveMemory,editMemory,forgetMemory,retrieveMemories,detectMemory,embedConfig} from '../src/memory/knowledge.js';
import {maintainKnowledge} from '../src/core/context.js';
import {needsWeb,validateClaims,runResearch} from '../src/research/research.js';
import {publicURL} from '../src/research/web-gateway.js';
async function req(env,path,body,method=body?'POST':'GET',user='alice'){return worker.fetch(new Request('https://veyro.test/api/'+path,{method,headers:{'oai-authenticated-user-id':user,'X-Veyro-Request':'1',origin:'https://veyro.test','Content-Type':'application/json'},body:body?JSON.stringify(body):undefined}),env);}
async function init(env){const p=await(await req(env,'projects',{title:'Teste'})).json();const c=await(await req(env,'conversations',{projectId:p.id})).json();return {pid:p.id,cid:c.id};}
const send=(env,cid,message)=>req(env,'conversations/'+cid+'/messages',{message,requestId:crypto.randomUUID()});
const responseJSON=d=>new Response('data: '+JSON.stringify({choices:[{delta:{content:JSON.stringify(d)}}]})+'\n\ndata: [DONE]\n\n');
const connected=env=>Object.assign(env,{MODEL_PROVIDER:'local',MODEL_BASE_URL:'https://model.example.org/v1',MODEL_NAME:'test',VEYRO_CHAT_ENABLED:'true'});
test('embeddings require an explicit non-OpenAI endpoint',()=>{assert.equal(embedConfig({VEYRO_EMBEDDINGS_ENABLED:'true',EMBEDDING_MODEL:'x',OPENAI_API_KEY:'legacy'}).ready,false);assert.equal(embedConfig({VEYRO_EMBEDDINGS_ENABLED:'true',EMBEDDING_MODEL:'x',EMBEDDING_BASE_URL:'http://127.0.0.1:11434/v1'}).ready,true);assert.equal(embedConfig({VEYRO_EMBEDDINGS_ENABLED:'true',EMBEDDING_MODEL:'x',EMBEDDING_BASE_URL:'http://example.org/v1'}).ready,false);});
test('memory variants save, resolve user referent, update and forget without a model',async()=>{const env=setup(),{pid,cid}=await init(env);for(const phrase of ['Lembre: use cenário medieval','Guarde isso: use cenário medieval','Memorize use cenário medieval','Não esqueça que use cenário medieval'])await(await send(env,cid,phrase)).text();assert.equal(env.sqlite.prepare('SELECT count(*) n FROM memories').get().n,1);await(await send(env,cid,'Atualize use cenário medieval para use cenário futurista')).text();assert.equal(env.sqlite.prepare('SELECT text FROM memories').get().text,'use cenário futurista');await(await send(env,cid,'Esqueça use cenário futurista')).text();assert.equal(env.sqlite.prepare('SELECT count(*) n FROM memories').get().n,0);await(await send(env,cid,'Meu personagem usa roupa azul')).text();await(await send(env,cid,'Guarde isso')).text();assert.equal(env.sqlite.prepare('SELECT text FROM memories').get().text,'Meu personagem usa roupa azul');assert.equal(basicMemoryIntent('Hoje pensei numa história').action,'NONE');});
test('four memory scopes, revisions and forgetting invalidate stale summaries',async()=>{const env=setup(),db=database(env),{pid,cid}=await init(env),other=await init(env);for(const scope of ['user','project','conversation','system'])await saveMemory(db,'alice',{text:scope,scope,projectId:pid,conversationId:cid});assert.equal((await retrieveMemories(db,env,'alice',pid,cid,'',20)).memories.length,4);assert.equal((await retrieveMemories(db,env,'alice',other.pid,other.cid,'',20)).memories.length,2);assert.equal((await retrieveMemories(db,env,'bob',pid,cid,'',20)).memories.length,0);const m=env.sqlite.prepare("SELECT * FROM memories WHERE scope='project'").get();await db.run("UPDATE conversations SET summary='old' WHERE id=?",cid);await editMemory(db,'alice',m.id,'new',m.revision);assert.equal(env.sqlite.prepare('SELECT summary FROM conversations WHERE id=?').get(cid).summary,'');await assert.rejects(editMemory(db,'alice',m.id,'stale',m.revision));await assert.rejects(forgetMemory(db,'bob',m.id));await forgetMemory(db,'alice',m.id);});
test('archiving, explicit manual title, pagination and deletion preserve project and general memory',async()=>{const env=setup(),db=database(env),{pid,cid}=await init(env);await saveMemory(db,'alice',{text:'project preference',projectId:pid});await saveMemory(db,'alice',{text:'temporary',scope:'conversation',conversationId:cid});await req(env,'conversations/'+cid,{title:'Nova conversa'},'PATCH');await(await send(env,cid,'Oi')).text();assert.equal((await(await req(env,'conversations/'+cid)).json()).conversation.title,'Nova conversa');await req(env,'conversations/'+cid,{archived:true},'PATCH');assert.equal((await(await req(env,'conversations')).json()).length,0);assert.equal((await(await req(env,'conversations?archived=1')).json()).length,1);assert.equal((await send(env,cid,'oi')).status,409);await req(env,'conversations/'+cid,{archived:false},'PATCH');assert.equal((await req(env,'conversations/'+cid,undefined,'DELETE','bob')).status,404);await req(env,'conversations/'+cid,undefined,'DELETE');assert.equal((await req(env,'conversations/'+cid)).status,404);assert.equal(env.sqlite.prepare('SELECT count(*) n FROM memories').get().n,1);assert.equal((await req(env,'projects/'+pid)).status,200);assert.equal((await(await req(env,'conversations')).json()).length,0);});
test('semantic vectors recover different words and memory updates discard outdated vectors',async()=>{const env=setup(),db=database(env),{pid,cid}=await init(env),m=await saveMemory(db,'alice',{text:'visual cinematográfico',projectId:pid});Object.assign(env,{VEYRO_EMBEDDINGS_ENABLED:'true',EMBEDDING_BASE_URL:'https://embed.example.org/v1',EMBEDDING_MODEL:'test-vector'});await db.run('UPDATE memories SET embedding=?,embedding_model=? WHERE id=?',JSON.stringify([1,0,0,0,0,0,0,0]),'test-vector',m.id);const old=globalThis.fetch;globalThis.fetch=async()=>Response.json({data:[{index:0,embedding:[1,0,0,0,0,0,0,0]}]});try{const result=await retrieveMemories(db,env,'alice',pid,cid,'aparência de filme');assert.equal(result.mode,'significado');assert.equal(result.memories[0].id,m.id);}finally{globalThis.fetch=old;}await editMemory(db,'alice',m.id,'outra preferência',0);assert.equal(env.sqlite.prepare('SELECT embedding FROM memories WHERE id=?').get(m.id).embedding,null);});
test('semantic memory action is constrained to owned IDs and no incidental saving',async()=>{const env=connected(setup()),old=globalThis.fetch;globalThis.fetch=async()=>responseJSON({action:'NONE'});try{const result=await detectMemory(env,'Salve a imagem em PNG',[],[]);assert.equal(result.action,'NONE');}finally{globalThis.fetch=old;}});
test('background titles honor manual rename and summaries store a cutoff',async()=>{const env=connected(setup()),db=database(env),{cid}=await init(env);env.VEYRO_KNOWLEDGE_ENABLED='true';for(let i=0;i<30;i++)await db.run('INSERT INTO chat_messages(id,conversation_id,role,text,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?)','m'+i,cid,i%2?'assistant':'user','Tema da cena '+i,'COMPLETE',i+1,i+1);const old=globalThis.fetch;globalThis.fetch=async(_,o)=>{const b=JSON.parse(o.body);return responseJSON(b.messages[0].content.includes('título')?{title:'Criação de cena medieval'}:{summary:'Cena medieval em revisão.'});};try{await maintainKnowledge(db,env,'alice',cid);let c=env.sqlite.prepare('SELECT * FROM conversations WHERE id=?').get(cid);assert.equal(c.title,'Criação de cena medieval');assert.equal(c.summary,'Cena medieval em revisão.');assert.ok(c.summary_through>0);await req(env,'conversations/'+cid,{title:'Meu título'},'PATCH');await maintainKnowledge(db,env,'alice',cid);assert.equal(env.sqlite.prepare('SELECT title FROM conversations WHERE id=?').get(cid).title,'Meu título');}finally{globalThis.fetch=old;}});
test('research decision, URL restrictions and exact evidence validation fail closed',()=>{assert.equal(needsWeb('Oi'),false);assert.equal(needsWeb('2 + 2'),false);assert.equal(needsWeb('Qual é a versão atual?'),true);assert.equal(needsWeb('Não pesquise na internet'),false);for(const u of ['http://example.com','https://127.0.0.1','https://2130706433','https://[::1]','https://foo.internal','https://x@google.com','https://metadata.google.internal','https://example.com:444'])assert.throws(()=>publicURL(u));assert.equal(publicURL('https://example.com/page?utm_source=x#a'),'https://example.com/page');const source={id:'s1',text:'O documento foi publicado em setembro de 2026.'};assert.equal(validateClaims({claims:[{text:'Fato',support:[{sourceId:'s1',quote:'inexistente aqui'}]}]},[source]).length,0);assert.equal(validateClaims({claims:[{text:'Fato',support:[{sourceId:'s1',quote:'publicado em setembro de 2026'}]}]},[source]).length,1);});
test('unconfigured research creates waiting record and never fabricates sources or memory',async()=>{const env=setup(),{cid}=await init(env);const s=await(await send(env,cid,'Pesquise a versão atual')).text();assert.ok(s.includes('event: waiting'));const r=env.sqlite.prepare('SELECT * FROM research_sessions').get();assert.equal(r.status,'WAITING');assert.equal(env.sqlite.prepare('SELECT count(*) n FROM research_sources').get().n,0);assert.equal(env.sqlite.prepare('SELECT count(*) n FROM memories').get().n,0);assert.equal((await req(env,'research/'+r.id,undefined,'GET','bob')).status,404);});
test('research reads sources, drops unsupported claims, keeps contradictions and survives a page failure',async()=>{const env=connected(setup()),db=database(env),{cid}=await init(env);Object.assign(env,{VEYRO_WEB_ENABLED:'true',SEARCH_BASE_URL:'https://search.example.org',WEB_READER_URL:'https://reader.example.org/read',WEB_READER_KEY:'test-only'});const old=globalThis.fetch;globalThis.fetch=async(url,o={})=>{if(String(url).startsWith(env.SEARCH_BASE_URL))return Response.json({results:[{url:'https://docs.example.org/release',title:'Versão atual'},{url:'https://official.example.org/release',title:'Versão atual documentação'},{url:'https://bad.example.org',title:'Página indisponível'}]});if(String(url)===env.WEB_READER_URL){const b=JSON.parse(o.body);if(b.url.includes('bad.'))return new Response('',{status:502});const text=b.url.includes('docs.')?'A versão estável é 2.0. O anúncio explica os recursos da atualização, a data e a compatibilidade do produto.':'O catálogo oficial lista versão estável 3.0. Este texto contém outra informação, divergente da documentação anterior, sem contexto cronológico claro.';return Response.json({url:b.url,title:'Documento',text,published:'2026-09-18'});}const b=JSON.parse(o.body),instruction=b.messages[0].content,data=JSON.parse(b.messages[1].content);if(instruction.includes('Extraia'))return responseJSON({claims:[{text:'Uma fonte informa versão 2.0.',support:[{sourceId:data.sources[0].id,quote:'A versão estável é 2.0.'}]},{text:'Inventado',support:[{sourceId:data.sources[0].id,quote:'Não existe esse trecho.'}]}]});return responseJSON({accepted:[0],answered:false,contradictions:['As fontes apresentam versões diferentes sem cronologia suficiente.'],warnings:[]});};try{const r=await runResearch(db,env,'alice',{query:'versão atual',mode:'QUICK',conversationId:cid});assert.equal(r.status,'INSUFFICIENT');assert.equal(r.sources.length,2);assert.equal(r.claims.length,1);assert.ok(r.answer.includes('[1]'));assert.ok(r.answer.includes('Divergências'));assert.ok(r.report.warnings.some(x=>x.includes('não puderam')));assert.equal(env.sqlite.prepare('SELECT count(*) n FROM memories').get().n,0);}finally{globalThis.fetch=old;}});
