import test from 'node:test';
import assert from 'node:assert/strict';
import {setup} from './helpers.mjs';
import worker from '../src/api/router.js';

async function request(env,path,{method='POST',body,user='alice'}={}){const headers={'oai-authenticated-user-id':user,'X-Veyro-Request':'1',origin:'https://veyro.test'};if(body&&!(body instanceof FormData))headers['content-type']='application/json';const res=await worker.fetch(new Request('https://veyro.test/api/'+path,{method,headers,body:body?(body instanceof FormData?body:JSON.stringify(body)):undefined}),env);return {status:res.status,data:await res.json()};}
const token='a'.repeat(64);
test('speech route requires configured local service and rejects unsafe audio types',async()=>{const env=setup();let r=await request(env,'speech/transcribe',{body:new FormData()});assert.equal(r.status,503);env.SPEECH_TOKEN=token;const form=new FormData();form.set('file',new File(['bad'],'bad.txt',{type:'text/plain'}));assert.equal((await request(env,'speech/transcribe',{body:form})).status,400);});
test('speech route only forwards to loopback and returns local transcription',async()=>{const env=setup();Object.assign(env,{SPEECH_TOKEN:token,SPEECH_BASE_URL:'http://127.0.0.1:8765'});const original=globalThis.fetch;let captured;globalThis.fetch=async(url,options)=>{captured={url,auth:options.headers.Authorization,form:options.body};return Response.json({text:'Olá Veyro',language:'pt',durationSeconds:2});};try{const form=new FormData();form.set('file',new File(['audio'],'voice.webm',{type:'audio/webm'}));form.set('language','pt');const r=await request(env,'speech/transcribe',{body:form});assert.equal(r.status,200);assert.equal(r.data.text,'Olá Veyro');assert.equal(captured.url,'http://127.0.0.1:8765/transcribe');assert.equal(captured.auth,'Bearer '+token);assert.ok(captured.form instanceof FormData);}finally{globalThis.fetch=original;}});
test('speech route refuses external transcription services',async()=>{const env=setup();Object.assign(env,{SPEECH_TOKEN:token,SPEECH_BASE_URL:'https://speech.example'});const form=new FormData();form.set('file',new File(['audio'],'voice.webm',{type:'audio/webm'}));assert.equal((await request(env,'speech/transcribe',{body:form})).status,503);});
test('translation uses local Qwen endpoint, detects source language and validates target',async()=>{const env=setup();Object.assign(env,{MODEL_PROVIDER:'local',MODEL_BASE_URL:'http://127.0.0.1:11434/v1',MODEL_NAME:'qwen3.5:4b',VEYRO_CHAT_ENABLED:'true'});const original=globalThis.fetch;let payload;globalThis.fetch=async(_url,options)=>{payload=JSON.parse(options.body);return new Response(`data: ${JSON.stringify({choices:[{delta:{content:JSON.stringify({detectedLanguage:'pt',translation:'Hello world'})}}]})}\n\ndata: [DONE]\n\n`);};try{const r=await request(env,'translate',{body:{text:'Olá mundo',sourceLanguage:'auto',targetLanguage:'en'}});assert.equal(r.status,200);assert.deepEqual(r.data,{translation:'Hello world',detectedLanguage:'pt',targetLanguage:'en'});assert.equal(payload.model,'qwen3.5:4b');assert.equal(payload.messages[1].content,'{"text":"Olá mundo"}');const invalid=await request(env,'translate',{body:{text:'Olá',sourceLanguage:'auto',targetLanguage:'auto'}});assert.equal(invalid.status,400);}finally{globalThis.fetch=original;}});
test('translation refuses nonlocal Qwen endpoints',async()=>{const env=setup();Object.assign(env,{MODEL_PROVIDER:'local',MODEL_BASE_URL:'https://model.example/v1',MODEL_NAME:'qwen',VEYRO_CHAT_ENABLED:'true'});const r=await request(env,'translate',{body:{text:'Bom dia',sourceLanguage:'auto',targetLanguage:'en'}});assert.equal(r.status,503);});
