import test from 'node:test';
import assert from 'node:assert/strict';
import {setup} from './helpers.mjs';
import worker from '../src/api/router.js';
import {cleanState} from '../src/core/domain.js';
import {intentHint} from '../src/media/studio-domain.js';
async function call(env,path,method='GET',data,user='alice'){const response=await worker.fetch(new Request('https://veyro.test/api/'+path,{method,headers:{'oai-authenticated-user-id':user,'x-veyro-request':'1','origin':'https://veyro.test'},body:data?JSON.stringify(data):undefined}),env);return {status:response.status,data:await response.json()};}
async function setupProject(){const env=setup(),r=await call(env,'projects','POST',{title:'Estúdio'});return {env,path:'projects/'+r.data.id,id:r.data.id};}
test('legacy snapshots gain empty studio fields and counts/time ranges are bounded',()=>{const s=cleanState({original:'Legado'});assert.equal(s.photo.count,1);assert.deepEqual(s.editor.clips,[]);assert.throws(()=>cleanState({photo:{count:6}}));assert.throws(()=>cleanState({editor:{clips:[{id:'a',assetId:'x',start:0,end:31,speed:1}]}}));assert.throws(()=>cleanState({editor:{clips:[{id:'a',assetId:'x',start:5,end:4,speed:1}]}}));});
test('image routing stays independent and does not steal video requests',()=>{for(const text of ['Quero só uma foto de uma floresta','Crie 5 imagens dessa cena','Troca o fundo dessa foto','Melhora essa foto, mas deixa natural','Cria uma thumbnail'])assert.equal(intentHint(text),'photo',text);assert.equal(intentHint('Crie um vídeo com fotos'),null);assert.equal(intentHint('Corta os 3 primeiros segundos do vídeo'),'editor');assert.equal(intentHint('Não quero criar uma foto'),null);});
test('photo request is persistent and isolated without calling an unconfigured API',async()=>{const {env,path}=await setupProject(),id=crypto.randomUUID(),settings={prompt:'Uma cidade futurista',count:5};const r=await call(env,path+'/photo-jobs','POST',{id,settings});assert.equal(r.status,201);assert.equal(r.data.status,'WAITING');assert.equal(r.data.request.count,5);assert.equal(r.data.request.sceneText,'');assert.equal((await call(env,path+'/photo-jobs/'+id,'GET',undefined,'bob')).status,404);assert.equal((await call(env,path+'/photo-jobs/'+id+'/run','POST',{})).status,503);assert.equal((await call(env,path)).data.photoJobs.length,1);assert.equal((await call(env,path+'/photo-jobs','POST',{id,settings})).data.id,id);});
test('timeline source validation rejects missing references and out-of-range cuts',async()=>{const {env,path,id}=await setupProject();env.sqlite.prepare('INSERT INTO assets VALUES(?,?,?,?,?,?,?,?)').run('video1',id,'video.mp4','video/mp4',100,'key',JSON.stringify({duration:10}),Date.now());let r=await call(env,path,'PUT',{revision:0,state:{editor:{clips:[{id:'a',assetId:'video1',start:2,end:11,speed:1}]}}});assert.equal(r.status,400);r=await call(env,path,'PUT',{revision:0,state:{editor:{clips:[{id:'a',assetId:'video1',start:2,end:8,speed:1.5}]},photo:{prompt:'Um cenário'}}});assert.equal(r.status,200);const saved=(await call(env,path)).data.project.state;assert.equal(saved.editor.clips[0].start,2);assert.equal(saved.photo.prompt,'Um cenário');});
test('no OpenAI image endpoint is available; image jobs remain saved and unconfigured',async()=>{const {env,path}=await setupProject();Object.assign(env,{OPENAI_API_KEY:'must-not-be-used',OPENAI_IMAGE_MODEL:'legacy-model',VEYRO_IMAGES_ENABLED:'true'});const id=crypto.randomUUID();const job=await call(env,path+'/photo-jobs','POST',{id,settings:{prompt:'Paisagem',count:2}});assert.equal(job.data.status,'WAITING');assert.equal((await call(env,path+'/photo-jobs/'+id+'/run','POST',{})).status,503);assert.equal((await call(env,'status')).data.images,false);});
